if shopt -q login_shell; then
  if [ -z "$SSH_CLIENT" ] || [ -z "$SSH_TTY" ]; then
    echo "Starting RaceCapture, Ctrl-c to abort!"
    for i in $(seq 2 -1 0)
    do
      echo -n $i
      sleep 1
      echo -ne '\b'
    done
    xinit -- -nocursor -dpms -s 0
  fi
fi
